### ISSUE TITLE
setupUnhandledExceptionHook swallows exceptions

### ISSUE THREAD

**Issue by PaulWoitaschek** [touchlab/Kermit#260]
Currently, the exception hooks do not propagate exceptions but rather swallows the kotlin exceptions.

This means that if the handler, set by `setupUnhandledExceptionHook` is called, the application does not crash. This is problematic because it brings the application in an unexpected state.

For example if you were to call a function like this from swift, the logger would be called but the application would not crash. 

```kotlin
public fun launchCrashApp() {
  GlobalScope.launch {
    delay(2.seconds)
    throw AssertionError("Here we die.")
  }
}
```

As kermit is advertised as:
> Kermit is a Kotlin Multiplatform logging utility

I recommend to throw the exception from within the library, i.e.

```kotlin
fun setupUnhandledExceptionHook(logger: Logger, onCrash: () -> String) {
    val unhandMe: ReportUnhandledExceptionHook = { t ->
        logger.e(t, onCrash)
        throw t
    }

    setUnhandledExceptionHook(unhandMe.freeze())
}
```

If this behavior is actually desired I suggest to rename the functions so they say what they do, i.e.
`setupSentryExceptionHookAndSwallowAllExceptions(Logger)`

**Comment by kpgalligan** [comment]
It's not desired behavior. I've had another report of this with Sentry, but I don't know if that has anything specific to do with Sentry or something is not working as it used to in Kotlin, but how we set the unhandled hook hasn't really changed. The unhandled hook previous would do nothing to prevent the app from crashing. It would only give you a place to do something before it did.

**Comment by kpgalligan** [comment]
Reference https://github.com/touchlab/Kermit/issues/257

**Comment by kpgalligan** [comment]
Well, as I said, it has worked with the other implementations, so I am confused as to why this wouldn't. That is unless something different happens in the context of a coroutine.

**Comment by PaulWoitaschek** [comment]
Let me see if I can put up a failing test case.

**Comment by kpgalligan** [comment]
Digging into it. The unhandled exception hook acts differently in the coroutines context. I'm not sure yet if that is just coroutines, or any background thread. It *also* looks like the unhandled exception handler was refactored in Kotlin 1.6.x. So, in the main thread, the exception handler runs then crashes as it used to, although the documentation around the unhandled exception would suggest that's not what should happen. I'm running a quick test pre-1.6.x, although I'm not sure that's worth it, and it I can't get it to compile quice I'll probably skip it and just move on.

In any case, the unhandled exception used to not need a rethrow of the exception, and currently also doesn't in the main thread, but apparently does in other threads. Digging in more for a bit as I'd like to understand this a bit better.

**Comment by kpgalligan** [comment]
OK, so that is effectively the situation. Kotlin 1.6.0 refactored the way the unhandled exception works, but only partially. In 1.5.32 (and earlier), the example you give does actually crash the app as expected.

The refactored unhandled exception *shouldn't* crash in any thread according to this: https://github.com/JetBrains/kotlin/commit/7e04bb4bf13ddfac25566ce33e7dba26b286533e#diff-ae447f0fe80276b0376b5e08b7e2a18023a441795e32a6b632a05daaf99cf278R75, but either because the main thread is handled differently, or because the crash is triggered with a UI action and that failed return path is actually causing the crash, our testing was all causing crashes but other contexts were not.

In any case, we'll need to do as you mentioned above, which conforms with the unhandled handler refactor, which is to re-throw the exception. It would also be a good idea to add some kind of crash tests, but that is difficult because they need to be run externally (the process falls over, so you can't test in-process).

**Comment by kpgalligan** [comment]
They do have some standalone tests in the kotlin source, but obviously setting that up requires some plumbing. I was knee deep in the Bugsnag refactor, but we'll need to publish a fix for this asap as it's, let's say, not great :)

If you have a test PR, that'll be very helpful, but I'll probably publish a fix in the interim and we can add a test PR soon after one way or the other.

**Comment by PaulWoitaschek** [comment]
The only sane idea I came up with for a test would be to create a separate module with a single test, and letting that test run and raise an exception in a coroutine.

The test itself would ofc. fail with the fix applied and it would be job of a script to ensure that the test failure contains the expected exception. I doubt that it's worth implementing this :/

**Comment by PaulWoitaschek** [comment]
Upstream issue:
https://youtrack.jetbrains.com/issue/KT-52908/Clarify-documentation-on-setUnhandledExceptionHook
