### ISSUE TITLE
Cannot use kermit-crashlytics in project with JVM target

### ISSUE THREAD

**Issue by dhoskins** [touchlab/Kermit#273]
Our project has a JVM target which we include in order to get code coverage for common Kotlin tests.

When running the tests we get the error:

```
* What went wrong:
Execution failed for task ':shared:compileKotlinJvm'.
> Error while evaluating property 'filteredArgumentsMap' of task ':shared:compileKotlinJvm'
   > Could not resolve all files for configuration ':shared:jvmCompileClasspath'.
      > Could not resolve co.touchlab:kermit-crashlytics:1.1.3.
        Required by:
            project :shared
         > No matching variant of co.touchlab:kermit-crashlytics:1.1.3 was found. The consumer was configured to find an API of a library, preferably optimized for standard JVMs, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but...
```

**Comment by mrf7** [comment]
Hi,`kermit-crashlytics` doesn't publish for pure JVM because Crashlytics doesn't support non Android JVM projects. So you wont be able to use `kermit-crashlytics` in `commonMain` if your project has the JVM target. If you want to keep the JVM target you'll have to move the `kermit-crashlytics` dependency into the `androidMain` source set
