### ISSUE TITLE
Define dependency versions

### ISSUE THREAD

**Issue by samhill303** [touchlab/Kermit#303]
It is difficult to keep versions of various dependencies, libraries, plugins, tools up to date in our various samples. We don't necessarily want to centralize too much because we don't want the configuration to make the sample confusing. But at least standardizing the version definitions between samples might make it easier to keep them up to date.

- Test using version catalogs in the samples
  - Decide if it's an acceptable pattern for the samples
- Test defining in gradle properties
- Test centralizing version catalog so all the samples pull from the same file
- Evaluate the pros/cons of the above options

**Comment by JuliaJakubcova** [comment]
### Version catalog in settings.gradle
Better than just defining versions in each build.gradle:
- Each version should be at this one place (for each sample) so it’s easier when updating
- Supports bundles
- Multiple dependencies can use same version
- Plugins can be declared as well
- Supports rich versions
- Autocompletion when using declared dependencies

### Version catalog as libs.versions.toml
- All of the advantages above
- Separate file for dependencies instead of contained in settings.gradle (better organization)

### Shared version catalog
- Dependencies for all samples in one place - less code, easier to update versions for all samples
- Disadvantage: if user downloads just one sample to use as a reference, he won’t find the dependencies and versions and it won’t work
- Can only be single file (enough for our use case)
