### ISSUE TITLE
Why is println and not _os_log_internal used here?

### ISSUE THREAD

**Issue by nbransby** [touchlab/Kermit#326]
https://github.com/touchlab/Kermit/blob/ea05457d4e5b062f1cf1cc9b2e68f61aab810606/kermit/src/darwinMain/kotlin/co/touchlab/kermit/OSLogWriter.kt#L42

Means we can't get the stacktrace from the logs unless running in debugger

**Comment by rocketraman** [comment]
The reason appears to be that logs are truncated when they are sent to the OS log.

Related discussion: https://github.com/touchlab/Kermit/issues/395.

**Comment by rocketraman** [comment]
Seems like this is no longer the case: https://github.com/touchlab/Kermit/blob/e87d7da197cac4c970d7309dd6b8486a401d886b/kermit-core/src/appleMain/kotlin/co/touchlab/kermit/OSLogWriter.kt#L58-L60.

Weirdly changed in a commit titled "Doc update".

**Comment by kpgalligan** [comment]
Correct. OSLogWriter sends everything to the system log. The `XcodeSeverityWriter` is the default, dev-focused log writer used if you don't modify the default Kermit config. The original issue indeed was that the system logger would truncate the stack trace, which often meant the info you really needed during dev wasn't available.

https://github.com/touchlab/Kermit/blob/e87d7da197cac4c970d7309dd6b8486a401d886b/kermit-core/src/appleMain/kotlin/co/touchlab/kermit/XcodeSeverityWriter.kt#L25

This has come up in various forms with various alternative solutions. For example, splitting the stack trace string so that each logging call was small enough to avoid being truncated, etc. Ultimately, the design decision was to have the `XcodeSeverityWriter` use println, as most devs are using Xcode visually. If you wanted something else specific and knew how to configure Kermit, extending `OSLogWriter` and overriding `logThrowable` is pretty simple, and seemed like a simpler approach than trying to come up with a solution that would make everybody happy.

Open to ideas, though.
