### ISSUE TITLE
Kermit not using default parameters in iOS with the version 2.0.0 and above

### ISSUE THREAD

**Issue by mustafaozhan** [touchlab/Kermit#373]
In the past, I was able to use the below in my iOS codebase:

```swift
	logger.i(message: { "Application init" })
```

but with the latest version it complains that I am missing the `tag` and the `throwable`. I created below extensions for now
```swift
extension KermitLogger {
    func i(message: @escaping () -> String) {
        self.i(throwable: nil, tag: "Kermit", message: message)
    }
    func d(message: @escaping () -> String) {
        self.d(throwable: nil, tag: "Kermit", message: message)
    }
    func w(message: @escaping () -> String) {
        self.w(throwable: nil, tag: "Kermit", message: message)
    }
    func v(message: @escaping () -> String) {
        self.v(throwable: nil, tag: "Kermit", message: message)
    }
    func e(message: @escaping () -> String) {
        self.e(throwable: nil, tag: "Kermit", message: message)
    }
    func a(message: @escaping () -> String) {
        self.a(throwable: nil, tag: "Kermit", message: message)
    }
}
```

But I think kermit should use the defaults, by default like before.

**Comment by KevinSchildhorn** [comment]
Can you double check if this is still occurring? We have `LoggerKt.i(string: "Hello from Swift")` in the kermit sample and that seems to work correctly.

**Comment by kpgalligan** [comment]
Kermit's design changed in 2.0. In previous versions, the public API had several extra methods in it, so that calling directly from Swift wouldn't require passing extra parameters. However, complicating the Kotlin API to support Swift (JS, others) seemed like bad API design.

In 2.0, if calling from Swift, there's another module `kermit-simple`, that includes the extra method definitions. The idea is if you wanted to call Kermit from Swift, you would export that API instead of the main Kermit API. Besides isolating that form of the API so that calling from Kotlin could use default params, exporting `kermit-simple` to iOS instead of the whole Kermit library would reduce the overall exported API surface, which would result in less unused binary being added to the final app.

https://github.com/touchlab/Kermit/blob/main/kermit-simple/src/nonKotlinMain/kotlin/co/touchlab/kermit/Logger.kt
