### ISSUE TITLE
Stack trace on iOS is not shown by default in the OS logs

### ISSUE THREAD

**Issue by rocketraman** [touchlab/Kermit#395]
I'm running a Kotlin multiplatform as a library within a React Native application.

With Kermit's default settings, which uses `XcodeSeverityWriter`, the stack trace is not shown anywhere. I'm looking in `Console.app`. However, according to https://stackoverflow.com/questions/10165641/how-can-i-get-the-console-logs-from-the-ios-simulator, standard output will only be shown in the XCode debug window.

This seems to be a poor default. Should the default be to use the `OSLogWriter` so that at least some stack trace is shown in all cases, and then allow users to specify `XcodeSeverityWriter` if they wish to see full traces in the XCode debug console?

**Comment by kpgalligan** [comment]
>  Should the default be to use the OSLogWriter so that at least some stack trace is shown in all cases, and then allow users to specify XcodeSeverityWriter if they wish to see full traces in the XCode debug console?

I would expect many more Xcode users to complain that the stack trace was truncated. Using a KMP library in a react native application would certainly seem to be the less likely scenario vs an iOS dev using a KMP library from Swift and Xcode. Would it not make sense to let you specify a different writer for an uncommon use case rather than making a less common use case the default?

**Comment by kpgalligan** [comment]
To follow up, that is what `OSLogWriter` is for. `XcodeSeverityWriter` is the "default" for iOS because 99% (guessing, but not far off) of people starting with KMP are running from Xcode. The default factory function `platformLogWriter`, as described in the comment describing it:

> Factory function to return a default LogWriter for each platform. The LogWriter is targeted at local development.

The variety of platform loggers makes a "sensible default" an exercise in compromise. Specifically the `XcodeSeverityWriter` adds color emojis, etc, to make it "more usable" from Xcode specifically.

**Comment by rocketraman** [comment]
That's fair. The logging situation on iOS seems to be a bit of a mess.

**Comment by kpgalligan** [comment]
They're all a mess in their own way. The xcode situation is weird, though.

I wonder if there's value in having different default functions. Not sure how it would work, but if you knew the consumer of the code would be calling from react native, you could call the "reactNativePlatformLogWriter()" factory function instead to init loggers inside the KMP code.
