### ISSUE TITLE
Order of log calls not preserved

### ISSUE THREAD

**Issue by DavidRobb** [touchlab/Kermit#401]
I an using version 2.0.4 in a desktop build on Windows using the Azul Zulu 21.0.1 SDK  and would expect log messages to come out in order regardless of log severity. When running
```kotlin
import co.touchlab.kermit.*

fun main() {

    Logger.e { "Log message-0" }
    Logger.w { "Log message-1" }
    Logger.i { "Log message-2" }
    Logger.e { "Log message-3" }
}
```
I see 

```
10:02:07: Executing 'desktopRun -DmainClass=LogKt --quiet'...

Warn: Log message-1
Info: Log message-2
Error: Log message-0
Error: Log message-3
10:02:08: Execution finished 'desktopRun -DmainClass=LogKt --quiet'.
```
Sometimes error messages are first, ither times last as shown.

**Comment by TadeasKriz** [comment]
`Error` is appended to `System.err` and others are appended to `System.out`. It might be reader of those streams that doesn't synchronize them correctly. Could you share the reproducer project so we can try on our systems? Thanks!

**Comment by DavidRobb** [comment]
OK. Here's an Intellij Idea project folder:
[KermitTest.zip](https://github.com/user-attachments/files/16362720/KermitTest.zip)

**Comment by TadeasKriz** [comment]
I believe the problem is in how Gradle forwards the system streams. If you run `./gradlew createDistributable` and then run the binary from terminal, the order of messages is correct always. I've had trouble with stream outputs in Gradle in the past.

If you add `System.setErr(System.stdout)` to `fun main()` (before you call `application`), you can see it prints it in the right order each time. Do not do that for a production app, it's just to show that Kermit doesn't control the order, it's whatever is reading from the streams.

**Comment by DavidRobb** [comment]
OK. Thanks for the explanation. Yes, this works for me.
